// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package db

import (
	"context"
	"time"
)

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT id, event_type_id, entity_type, entity_id, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT ?
`

type GetAuditLogsRow struct {
	ID          int64
	EventTypeID int64
	EntityType  string
	EntityID    string
	CreatedAt   *time.Time
}

func (q *Queries) GetAuditLogs(ctx context.Context, limit int64) ([]GetAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditLogsRow
	for rows.Next() {
		var i GetAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTypeID,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByEntity = `-- name: GetAuditLogsByEntity :many
SELECT id, event_type_id, entity_type, entity_id, created_at
FROM audit_logs
WHERE entity_id = ? AND entity_type = ?
ORDER BY created_at DESC
`

type GetAuditLogsByEntityParams struct {
	EntityID   string
	EntityType string
}

type GetAuditLogsByEntityRow struct {
	ID          int64
	EventTypeID int64
	EntityType  string
	EntityID    string
	CreatedAt   *time.Time
}

func (q *Queries) GetAuditLogsByEntity(ctx context.Context, arg GetAuditLogsByEntityParams) ([]GetAuditLogsByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByEntity, arg.EntityID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditLogsByEntityRow
	for rows.Next() {
		var i GetAuditLogsByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTypeID,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (event_type_id, entity_type, entity_id)
VALUES (?, ?, ?)
`

type InsertAuditLogParams struct {
	EventTypeID int64
	EntityType  string
	EntityID    string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog, arg.EventTypeID, arg.EntityType, arg.EntityID)
	return err
}
