// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: licenses.sql

package db

import (
	"context"
)

const claimLicenseNodeWithPoolFIFO = `-- name: ClaimLicenseNodeWithPoolFIFO :one
INSERT INTO license_nodes (license_id, node_id)
SELECT l.id, ?
FROM licenses l
WHERE l.pool_id = ?
  AND (SELECT COUNT(*) FROM license_nodes ln WHERE ln.license_id = l.id) < l.seats
ORDER BY l.created_at ASC
LIMIT 1
RETURNING license_id
`

type ClaimLicenseNodeWithPoolFIFOParams struct {
	NodeID int64
	PoolID *int64
}

func (q *Queries) ClaimLicenseNodeWithPoolFIFO(ctx context.Context, arg ClaimLicenseNodeWithPoolFIFOParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimLicenseNodeWithPoolFIFO, arg.NodeID, arg.PoolID)
	var license_id int64
	err := row.Scan(&license_id)
	return license_id, err
}

const claimLicenseNodeWithPoolLIFO = `-- name: ClaimLicenseNodeWithPoolLIFO :one
INSERT INTO license_nodes (license_id, node_id)
SELECT l.id, ?
FROM licenses l
WHERE l.pool_id = ?
  AND (SELECT COUNT(*) FROM license_nodes ln WHERE ln.license_id = l.id) < l.seats
ORDER BY l.created_at DESC
LIMIT 1
RETURNING license_id
`

type ClaimLicenseNodeWithPoolLIFOParams struct {
	NodeID int64
	PoolID *int64
}

func (q *Queries) ClaimLicenseNodeWithPoolLIFO(ctx context.Context, arg ClaimLicenseNodeWithPoolLIFOParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimLicenseNodeWithPoolLIFO, arg.NodeID, arg.PoolID)
	var license_id int64
	err := row.Scan(&license_id)
	return license_id, err
}

const claimLicenseNodeWithPoolRandom = `-- name: ClaimLicenseNodeWithPoolRandom :one
INSERT INTO license_nodes (license_id, node_id)
SELECT l.id, ?
FROM licenses l
WHERE l.pool_id = ?
  AND (SELECT COUNT(*) FROM license_nodes ln WHERE ln.license_id = l.id) < l.seats
ORDER BY RANDOM()
LIMIT 1
RETURNING license_id
`

type ClaimLicenseNodeWithPoolRandomParams struct {
	NodeID int64
	PoolID *int64
}

func (q *Queries) ClaimLicenseNodeWithPoolRandom(ctx context.Context, arg ClaimLicenseNodeWithPoolRandomParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimLicenseNodeWithPoolRandom, arg.NodeID, arg.PoolID)
	var license_id int64
	err := row.Scan(&license_id)
	return license_id, err
}

const claimLicenseNodeWithoutPoolFIFO = `-- name: ClaimLicenseNodeWithoutPoolFIFO :one
INSERT INTO license_nodes (license_id, node_id)
SELECT l.id, ?
FROM licenses l
WHERE l.pool_id IS NULL
  AND (SELECT COUNT(*) FROM license_nodes ln WHERE ln.license_id = l.id) < l.seats
ORDER BY l.created_at ASC
LIMIT 1
RETURNING license_id
`

func (q *Queries) ClaimLicenseNodeWithoutPoolFIFO(ctx context.Context, nodeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimLicenseNodeWithoutPoolFIFO, nodeID)
	var license_id int64
	err := row.Scan(&license_id)
	return license_id, err
}

const claimLicenseNodeWithoutPoolLIFO = `-- name: ClaimLicenseNodeWithoutPoolLIFO :one
INSERT INTO license_nodes (license_id, node_id)
SELECT l.id, ?
FROM licenses l
WHERE l.pool_id IS NULL
  AND (SELECT COUNT(*) FROM license_nodes ln WHERE ln.license_id = l.id) < l.seats
ORDER BY l.created_at DESC
LIMIT 1
RETURNING license_id
`

func (q *Queries) ClaimLicenseNodeWithoutPoolLIFO(ctx context.Context, nodeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimLicenseNodeWithoutPoolLIFO, nodeID)
	var license_id int64
	err := row.Scan(&license_id)
	return license_id, err
}

const claimLicenseNodeWithoutPoolRandom = `-- name: ClaimLicenseNodeWithoutPoolRandom :one
INSERT INTO license_nodes (license_id, node_id)
SELECT l.id, ?
FROM licenses l
WHERE l.pool_id IS NULL
  AND (SELECT COUNT(*) FROM license_nodes ln WHERE ln.license_id = l.id) < l.seats
ORDER BY RANDOM()
LIMIT 1
RETURNING license_id
`

func (q *Queries) ClaimLicenseNodeWithoutPoolRandom(ctx context.Context, nodeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimLicenseNodeWithoutPoolRandom, nodeID)
	var license_id int64
	err := row.Scan(&license_id)
	return license_id, err
}

const deleteLicenseByGUID = `-- name: DeleteLicenseByGUID :one
DELETE FROM licenses
WHERE guid = ?
RETURNING id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
`

func (q *Queries) DeleteLicenseByGUID(ctx context.Context, guid string) (License, error) {
	row := q.db.QueryRowContext(ctx, deleteLicenseByGUID, guid)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenseByGUID = `-- name: GetLicenseByGUID :one
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
WHERE guid = ?
`

func (q *Queries) GetLicenseByGUID(ctx context.Context, guid string) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByGUID, guid)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenseByID = `-- name: GetLicenseByID :one
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
WHERE id = ?
`

func (q *Queries) GetLicenseByID(ctx context.Context, id int64) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByID, id)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenseByNodeIDWithPool = `-- name: GetLicenseByNodeIDWithPool :one
SELECT l.id, l.guid, l.file, l."key", l.claims, l.last_claimed_at, l.last_released_at, l.seats, l.pool_id, l.created_at, l.public_key
FROM licenses l
JOIN license_nodes ln ON ln.license_id = l.id
WHERE ln.node_id = ? AND l.pool_id = ?
LIMIT 1
`

type GetLicenseByNodeIDWithPoolParams struct {
	NodeID int64
	PoolID *int64
}

func (q *Queries) GetLicenseByNodeIDWithPool(ctx context.Context, arg GetLicenseByNodeIDWithPoolParams) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByNodeIDWithPool, arg.NodeID, arg.PoolID)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenseByNodeIDWithoutPool = `-- name: GetLicenseByNodeIDWithoutPool :one
SELECT l.id, l.guid, l.file, l."key", l.claims, l.last_claimed_at, l.last_released_at, l.seats, l.pool_id, l.created_at, l.public_key
FROM licenses l
JOIN license_nodes ln ON ln.license_id = l.id
WHERE ln.node_id = ? AND l.pool_id IS NULL
LIMIT 1
`

func (q *Queries) GetLicenseByNodeIDWithoutPool(ctx context.Context, nodeID int64) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByNodeIDWithoutPool, nodeID)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenseWithPoolByGUID = `-- name: GetLicenseWithPoolByGUID :one
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
WHERE guid = ? AND pool_id = ?
`

type GetLicenseWithPoolByGUIDParams struct {
	Guid   string
	PoolID *int64
}

func (q *Queries) GetLicenseWithPoolByGUID(ctx context.Context, arg GetLicenseWithPoolByGUIDParams) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseWithPoolByGUID, arg.Guid, arg.PoolID)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenseWithoutPoolByGUID = `-- name: GetLicenseWithoutPoolByGUID :one
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
WHERE guid = ? AND pool_id IS NULL
`

func (q *Queries) GetLicenseWithoutPoolByGUID(ctx context.Context, guid string) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseWithoutPoolByGUID, guid)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const getLicenses = `-- name: GetLicenses :many
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
ORDER BY id
`

func (q *Queries) GetLicenses(ctx context.Context) ([]License, error) {
	rows, err := q.db.QueryContext(ctx, getLicenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []License
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.File,
			&i.Key,
			&i.Claims,
			&i.LastClaimedAt,
			&i.LastReleasedAt,
			&i.Seats,
			&i.PoolID,
			&i.CreatedAt,
			&i.PublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicensesWithPool = `-- name: GetLicensesWithPool :many
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
WHERE pool_id = ?
ORDER BY id
`

func (q *Queries) GetLicensesWithPool(ctx context.Context, poolID *int64) ([]License, error) {
	rows, err := q.db.QueryContext(ctx, getLicensesWithPool, poolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []License
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.File,
			&i.Key,
			&i.Claims,
			&i.LastClaimedAt,
			&i.LastReleasedAt,
			&i.Seats,
			&i.PoolID,
			&i.CreatedAt,
			&i.PublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicensesWithoutPool = `-- name: GetLicensesWithoutPool :many
SELECT id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
FROM licenses
WHERE pool_id IS NULL
ORDER BY id
`

func (q *Queries) GetLicensesWithoutPool(ctx context.Context) ([]License, error) {
	rows, err := q.db.QueryContext(ctx, getLicensesWithoutPool)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []License
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.File,
			&i.Key,
			&i.Claims,
			&i.LastClaimedAt,
			&i.LastReleasedAt,
			&i.Seats,
			&i.PoolID,
			&i.CreatedAt,
			&i.PublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementLicenseClaims = `-- name: IncrementLicenseClaims :exec
UPDATE licenses
SET claims = claims + 1, last_claimed_at = unixepoch()
WHERE id = ?
`

func (q *Queries) IncrementLicenseClaims(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementLicenseClaims, id)
	return err
}

const insertLicense = `-- name: InsertLicense :one
INSERT INTO licenses (pool_id, guid, file, key, seats, public_key)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, guid, file, "key", claims, last_claimed_at, last_released_at, seats, pool_id, created_at, public_key
`

type InsertLicenseParams struct {
	PoolID    *int64
	Guid      string
	File      []byte
	Key       string
	Seats     int64
	PublicKey string
}

func (q *Queries) InsertLicense(ctx context.Context, arg InsertLicenseParams) (License, error) {
	row := q.db.QueryRowContext(ctx, insertLicense,
		arg.PoolID,
		arg.Guid,
		arg.File,
		arg.Key,
		arg.Seats,
		arg.PublicKey,
	)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.File,
		&i.Key,
		&i.Claims,
		&i.LastClaimedAt,
		&i.LastReleasedAt,
		&i.Seats,
		&i.PoolID,
		&i.CreatedAt,
		&i.PublicKey,
	)
	return i, err
}

const releaseLicenseNodeWithPoolByNodeID = `-- name: ReleaseLicenseNodeWithPoolByNodeID :exec
DELETE FROM license_nodes
WHERE node_id = ?
  AND license_id IN (SELECT id FROM licenses WHERE pool_id = ?)
`

type ReleaseLicenseNodeWithPoolByNodeIDParams struct {
	NodeID int64
	PoolID *int64
}

func (q *Queries) ReleaseLicenseNodeWithPoolByNodeID(ctx context.Context, arg ReleaseLicenseNodeWithPoolByNodeIDParams) error {
	_, err := q.db.ExecContext(ctx, releaseLicenseNodeWithPoolByNodeID, arg.NodeID, arg.PoolID)
	return err
}

const releaseLicenseNodeWithoutPoolByNodeID = `-- name: ReleaseLicenseNodeWithoutPoolByNodeID :exec
DELETE FROM license_nodes
WHERE node_id = ?
  AND license_id IN (SELECT id FROM licenses WHERE pool_id IS NULL)
`

func (q *Queries) ReleaseLicenseNodeWithoutPoolByNodeID(ctx context.Context, nodeID int64) error {
	_, err := q.db.ExecContext(ctx, releaseLicenseNodeWithoutPoolByNodeID, nodeID)
	return err
}

const releaseLicenseNodesFromDeadNodes = `-- name: ReleaseLicenseNodesFromDeadNodes :many
DELETE FROM license_nodes
WHERE node_id IN (
    SELECT id FROM nodes
    WHERE last_heartbeat_at <= strftime('%s', 'now', ?) AND deactivated_at IS NULL
)
RETURNING license_id
`

func (q *Queries) ReleaseLicenseNodesFromDeadNodes(ctx context.Context, strftime interface{}) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, releaseLicenseNodesFromDeadNodes, strftime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var license_id int64
		if err := rows.Scan(&license_id); err != nil {
			return nil, err
		}
		items = append(items, license_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLicenseLastReleasedAt = `-- name: TouchLicenseLastReleasedAt :exec
UPDATE licenses
SET last_released_at = unixepoch()
WHERE id = ?
`

func (q *Queries) TouchLicenseLastReleasedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchLicenseLastReleasedAt, id)
	return err
}
