// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: license_nodes.sql

package db

import (
	"context"
)

const getLicenseNodeCount = `-- name: GetLicenseNodeCount :one
SELECT COUNT(*) FROM license_nodes WHERE license_id = ?
`

func (q *Queries) GetLicenseNodeCount(ctx context.Context, licenseID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLicenseNodeCount, licenseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
