// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID         int64
	Action     string
	EntityType string
	EntityID   string
	Timestamp  sql.NullString
}

type License struct {
	ID             string
	File           []byte
	Key            string
	Claims         int64
	LastClaimedAt  sql.NullString
	LastReleasedAt sql.NullString
	NodeID         sql.NullInt64
}

type Node struct {
	ID              int64
	Fingerprint     string
	ClaimedAt       sql.NullString
	LastHeartbeatAt sql.NullString
}
