name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Install sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.27.0'
      - name: Build
        run: make build
      - name: Vet
        run: make vet
      - name: Fmt
        run: test -z "$(make fmt)"
      - name: Test
        run: make test-all
